paradise/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('web.urls')),
    url(r'^web/', include('web.urls', namespace="web")),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns = [
    url(r'^', include('web.urls')),
    url(r'^web/', include('web.urls', namespace="web")),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
#    url(r'^$', views.review_list, name='review_list'),
    url(r'^$', views.home, name='home'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    # ex: /product/
    url(r'^product$', views.product_list, name='product_list'),
    # ex: /product/5/
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<product_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    # ex: /about/
    url(r'^about$', views.about_detail, name='about_detail'),
    url(r'^contact$', views.contact_detail, name='contact_detail'),
    url(r'^why$', views.why_detail, name='why_detail'),
    url(r'^faq$', views.faq_detail, name='faq_detail'),

    
]

web/models.py
from __future__ import unicode_literals

from django.db import models
from tinymce import models as tinymce_models
import numpy as np

def upload_location(obj, filename):
    return "%s/%s" %(obj.id, filename)
    
class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="")
    image = models.ImageField(upload_to = upload_location, null=True, blank=True)
    link1_title = models.CharField(max_length=100, blank=True)
    link1_link = models.CharField(max_length=200, blank=True, help_text="Make sure the link starts with 'https://'")
    link2_title = models.CharField(max_length=200, blank=True)
    link2_link = models.CharField(max_length=200, blank=True, help_text="Make sure the link starts with 'https://'")

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __unicode__(self):
        return self.name
#
class Announcement(models.Model):
    title = models.CharField(max_length=200)
    content = tinymce_models.HTMLField()
    pub_date = models.DateTimeField('date published')
    image1 = models.ImageField(upload_to = upload_location, null=True, blank=True) 
    image2 = models.ImageField(upload_to = upload_location, null=True, blank=True) 
    image3 = models.ImageField(upload_to = upload_location, null=True, blank=True) 
    image4 = models.ImageField(upload_to = upload_location, null=True, blank=True) 

class Test(models.Model):
    name = models.CharField(max_length=100)
class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    product = models.ForeignKey(Product)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)

web/forms.py
#from django import forms
from django.forms import ModelForm, Textarea
from web.models import Review
#from tinymce.widgets import TinyMCE

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15})
        }


#class ProductForm(ModelForm):
#    class Meta:
#        model = Wine
#        fields = ["image"]
        
#class AnnouncementForm(ModelForm):
#    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
#    class Meta:
#        model = Announcement
#        
 
        
    

web/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Review, Product, Announcement
from .forms import ReviewForm
import datetime


def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'web/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'web/review_detail.html', {'review': review})


def product_list(request):
    product_list = Product.objects.order_by('-name')
    context = {'product_list':product_list}
    return render(request, 'web/product_list.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm()
    return render(request, 'web/product_detail.html', {'product': product})

def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = form.cleaned_data['user_name']
        review = Review()
        review.product = product
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('web:product_detail', args=(product.id,)))

    return render(request, 'web/product_detail.html', {'product': product, 'form': form})
    
def about_detail(request):
    context = {'about_detail':about_detail}
    return render(request, 'web/about_detail.html', context)

def faq_detail(request):
    context = {'faq_detail':faq_detail}
    return render(request, 'web/faq_detail.html', context)

def why_detail(request):
    context = {'why_detail':why_detail}
    return render(request, 'web/why_detail.html', context)

def contact_detail(request):
    context = {'why_detail':why_detail}
    return render(request, 'web/contact_detail.html', context)

def home(request):
    announcement_list = Announcement.objects.order_by('-pub_date')[:9]
    context = {'announcement_list':announcement_list}
    return render(request, 'web/home.html', context)

paradise/reviews/templates/reviews/wine_detail.html
{% extends 'reviews/base.html' %}
{% load static%}
{% load bootstrap3 %}

{% block title %}

{% endblock %}

{% block content %}

<div class="page-header">
      <h3>Our Products</h3>
    </div>

<div class="container-fluid">
<div class="row">
<div class="page-header">
    <h2>{{ wine.name }}</h2>
    <h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
</div>
    </div>
<div class="row">
<h3>Recent reviews</h3>
    </div>
<div class="row">
{% if wine.review_set.all %}
    {% for review in wine.review_set.all %}
    <div>
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}
</div>

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {% for field in form %}
    {% bootstrap_field field %}
{% endfor %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
</div>

{% endblock %}

web/templates/web/about_detail.html
{% extends 'web/base.html' %}
{% load static%}
{% block title %}{% endblock %}

{% block content %}

<div class="page-header">
      <h3>Our Mission</h3>
    </div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <p class="lead">We believe in holistic farming. Over the years, with the advancement of civilization, our food has completely changed from the food of our ancestors. Our goal is to establisha a real farm (rather than a factory) that produces fresh, natural, and healthy food.

                <div class="bs-callout bs-callout-primary">
                    <h4>Animals</h4> Animals at Green Nature Farm roam freely within their open and spacious pens. They eat feed free of hormones and antibiotics. You can taste the difference.
                </div>
                <div class="bs-callout bs-callout-success"> 
                        <h4>Plants</h4> We use absolutely no herbicides and insecticides on our plants. Doing so reduces our harvest but any other way of farming is not natural. High quality food comes at a cost. We use crop rotation as a natural method of increasing yield.
                </div>
            <div class="row">
                <div class="about-attributes">
                <div class="col-md-2 col-xs-1">
                </div>
                <div class="col-md-4 col-xs-5">
                <p><strong>Our vegetables are:</strong>

                        <br>Non-GMO
                        <br>No herbicides
                        <br>No pesticides
                        <br>Freshly picked
                        <br>Naturally ripened
                        <br>No preservatives
                        </p>
                </div>
                <div class="col-md-4 col-xs-5">
                    <strong>Our chickens, ducks and geese are:</strong>

                        <br>Free range with access to green pasture
                        <br>No growth hormones
                        <br>No antibiotics
                        <br>No medications
                        <br>Humanely treated 
                </div>
                <div class="col-md-2 col-xs-1">
                </div>
                    </div>
            </div>
            <br>

                <div class="jumbotron">
                    <h1>Interested?</h1>
                    <p>Check out our list of products! </p>
                    <p><a class="btn btn-primary btn-lg" href="{% url 'web:product_list' %}" role="button">Learn more</a></p>
                </div>
            <br><br>

        </div>
        <div class="col-md-3">
            <div class="about-images">
                <div class="row">
                    <div class="col-md-12 col-xs-6">
                        <a href="#" class="thumbnail">
                        <img src="{% static 'web/image/carrots_original_main.jpg' %}" alt="...">        </a>
                    </div>
                    <div class="col-md-12 col-xs-6">
                        <a href="#" class="thumbnail">
                        <img src="{% static 'web/image/drone_land.jpg' %}" alt="..."></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col-md-3 -->
    </div>
    <!-- /.row -->
    
<div class="page-header">
      <h3>Where are we?</h3>
</div>
    
<div class="row">
    <div class="col-md-7 col-xs-6">

    <p class="lead">Our address is <strong>10590 Cook Brothers Road, Ijamsville, MD 21754.</strong> <br> <br>Located in Frederick County, we are about 10 minutes outside of Clarksburg.
    <br> <br>
    </div>

    <div class="col-md-5 col-xs-6">
        <a href="#" class="thumbnail">
      <img src="{% static 'web/image/maps-greennature.jpg' %}" alt="...">
    </a>
    </div>
</div>
    



{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap3 %} {% bootstrap_css %} {% bootstrap_javascript %} {% load staticfiles %}
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'web/style.css' %}"> {% block bootstrap3_content %}
<div class="container">

<nav>
    <div id="nav">
        <div id="nav_wrapper">
<!--            <nav class="collapse navbar-collapse">-->
            <ul>
                <li><img src="{% static 'web/image/greenacrelogo.png' %}" class="img-responsive img-thumbnail"></li>
                <li><a href="{% url 'web:home' %}">Home</a></li>
                <li><a href="{% url 'web:about_detail' %}">About</a></li>
                <li><a href="{% url 'web:product_list' %}">Product List</a></li>
                <li><a href="{% url 'web:faq_detail' %}">FAQ</a>
<!--
                    <ul>
                        <li><a href="#">dropdown #1 item #1</a>
                        </li>
                    </ul>
-->
                </li>
                <li><a href="{% url 'web:why_detail' %}">Safe & Healthy Food</a></li>
                <li><a href="{% url 'web:contact_detail' %}">Contact</a></li>
<!--                <li><img src="{% static 'web/image/greenacrelogo.png' %}" class="img-responsive img-thumbnail"></li>-->
            </ul>
<!--            </nav>-->
        </div>
    </div>
</nav>
    
</div>
    

<h1>{% block title %}(no title){% endblock %}</h1> {% bootstrap_messages %} {% block content %}(no content){% endblock %}


{% endblock %}

    <!-- Footer -->
  <footer class="uc-footer" role="contentinfo">
    <div class="container">
      <div class="uc-social">
        <ul class="uc-social-buttons">
          <li><iframe class="github-btn" src="//ghbtns.com/github-btn.html?user=jtang495&repo=green-nature&type=watch&count=true" width="75" height="20" title="Star on Github"></iframe>
          <li><iframe class="github-btn" src="//ghbtns.com/github-btn.html?user=jtang495&repo=green-nature&type=follow&count=true" width="150" height="20" title="Follow on Github"></iframe>
<!--          <li class="follow-btn"><a href="//twitter.com/UCDolphins" class="twitter-follow-button" data-link-color="#0069D6" data-show-count="true">Follow @UCDolphins</a>-->
        </ul><!-- /.uc-social-buttons -->
      </div><!-- /.uc-social -->
      <p>© 2016 Green Nature Farm. 10590 Cook Brothers Road, Ijamsville, MD 21754 - Phone/Text: (240)-432-8787
      <ul class="footer-links">
        <li>Site version 1.0
        <li class="muted">·
        <li><a href="//www.github.com/jtang495/green-nature" target="_blank">Github Project</a>
        <li class="muted">·
        <li>Created by Jason Tang
      </ul>
    </div><!-- /.container -->
  </footer><!-- /.uc-footer -->
    
</html>

web/templates/web/contact_detail.html
{% extends 'web/base.html' %}
{% load static%}
{% block title %}{% endblock %}

{% block content %}

<div class="page-header">
          <h3>Contact</h3>
        </div>
<div class="container-fluid">
    <div class="row">
        <div class="contact-attributes">
            <div class="col-md-4">
                <h1>Contact</h1> Email: services@greennaturefarm.com

                <br>Facebook: https://www.facebook.com/greennaturefarm
                <br>Web: http://www.greennaturefarm.com
                <br>We-Chat ID: greennaturefarm
                <br>Phone/Text: (240)-432-8787
            </div>
            <div class="col-md-4">
                <h1>Address</h1>
                <h5>10590 Cook Brothers Road, Ijamsville, MD 21754</h5>
            </div>
            <div class="col-md-4">
                <h1>Hours</h1> Our hours vary during the year. Please contact us first.
            </div>
        </div>
    </div>
</div>
<br>
<hr><!--<hr> - liner to seperate page-->
<br>
<div class="contact-banner">
    
</div>
{% endblock %}

web/templates/web/faq_detail.html
{% extends 'web/base.html' %}

{% load static %}
{% block title %}

{% endblock %}

{% block content %}

<div class="page-header">
      <h3>Frequently Asked Questions</h3>
    </div>

<div class="container-fluid">
    <div class="row">
    <div class="col-md-8">
    <div class="bs-callout bs-callout-primary">
        <h4>May I pick my own vegetables? </h4>Yes. We welcome our customers to pick up their own vegetables and fruits. But you must make an appointment  (contact)
        </div>
    <div class="bs-callout bs-callout-success">
        <h4>Can I make reservations?</h4> Yes. We welcome reservations from you. We can prepare the produce ready for pick up at set time so that you can save time.
    </div>
    <div class="bs-callout bs-callout-primary">
        <h4>Is your farm certified? </h4>Yes.  We are a registered farm in Maryland and are authorized to produce and sell farm produce and foods to the public.
        </div>
    <div class="bs-callout bs-callout-success">
        <h4>Who is responsible for accidents at the farm? </h4> Although we take care to make our farm a safe place, please acknowledge that a farm is an inherently dangerous work place where people can get hurt in many ways. We are not responsible for any bodily and property accidents and damages at our farm. Those who are concerned should not enter our farm and can use our off-farm distribution service to purchase our farm produce. 
    </div>
    </div>
        
    <div class="col-md-3 col-xs-4">
        <br>
    <img src="{% static 'web/image/greenacre.png' %}" class="img-responsive">
    </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-xs-2">
        </div>
        <div class="col-md-6 col-xs-8">
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="{% static 'web/image/drone_land.jpg' %}" alt="Chania" class = "img-resposive">
    </div>

    <div class="item">
      <img src="{% static 'web/image/geese.jpg' %}" alt="Chania" class = "img-resposive">
    </div>

    <div class="item">
      <img src="{% static 'web/image/fieldofplants.jpg' %}" alt="Flower" class = "img-resposive">
    </div>

    <div class="item">
      <img src="{% static 'web/image/Corn.jpg' %}" alt="Flower" class = "img-resposive">
    </div>
      
    <div class="item">
      <img src="{% static 'web/image/drone_farm.jpg' %}" alt="Flower" class = "img-resposive">
    </div>
      
    <div class="item">
      <img src="{% static 'web/image/drone_sky.jpg' %}" alt="Flower" class = "img-resposive">
    </div>
      
    <div class="item">
      <img src="{% static 'web/image/drone_geese.jpg' %}" alt="Flower" class = "img-resposive">
    </div>
  </div>

<!--   Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        </div>
         <div class="col-md-3 col-xs-2">
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
<script> $('#myCarousel').carousel({ interval: 3000 }) </script>


{% endblock %}

web/templates/web/home.html
{% extends 'web/base.html' %}

{% load static %}
{% block title %}

{% endblock %}

{% block content %}



<div class="home_container">
    
    <div class="home_banner">
        <div class="home_text">
    <h2><strong>Green Nature Farm</strong></h2>
    <h1>A family-friendly farm based in Southern Frederick, Maryland</h1>
        </div>
    </div> 
</div>

<!--
<div class="page-header">
      <h1> Home</h1>
    </div>

<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
  <p>Blessed with two growth seasons each year, we grow a variety of spring/summer or fall/winter vegetables year-round.  Find out more about the health benefits of seasonal and locally-grown food. </p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'web:why_detail' %}" role="button">Learn more</a></p>
  </div>
</div>
-->
 
<div class="page-header">
      <h1>Announcements</h1>
    </div>



<div class="container-fluid">

{% if announcement_list %}
    {% for announcement in announcement_list %}
    <div class="row">
        <div class="bs-callout bs-callout-blog">
            <h2>{{ announcement.title }}</h2>
            <p>{{ announcement.content|safe }}</p>
            <h5>{{ announcement.pub_date }}</h5>
        </div>
    </div>
    <div class="row">
<!--         Very cumbersome manual implementation of files. For future implement new image model -->
        {% if announcement.image1 %}
            <div class="col-md-3 col-sm-4 col-xs-6">
        <a href="#" class="thumbnail">
        <img src='{{ announcement.image1.url }}' class='img-responsive' /></a>
            </div>
        {% endif %}
        {% if announcement.image2 %}
            <div class="col-md-3 col-sm-4 col-xs-6">
        <a href="#" class="thumbnail">
        <img src='{{ announcement.image2.url }}' class='img-responsive' /></a>
            </div>
        {% endif %}
        {% if announcement.image3 %}
            <div class="col-md-3 col-sm-4 col-xs-6">
        <a href="#" class="thumbnail">
        <img src='{{ announcement.image3.url }}' class='img-responsive' /></a>
            </div>
        {% endif %}
        {% if announcement.image4 %}
            <div class="col-md-3 col-sm-4 col-xs-6">
        <a href="#" class="thumbnail">
        <img src='{{ announcement.image4.url }}' class='img-responsive' /></a>
            </div>
        {% endif %}
    </div>
    <hr>
    {% endfor %}
{% endif %}

</div>


{% endblock %}

web/templates/web/product_detail.html
{% extends 'web/base.html' %}
{% load static%}
{% load bootstrap3 %}

{% block title %}

{% endblock %}

{% block content %}

<div class="page-header">
      <h3>Our Products</h3>
    </div>

<div class="container-product">
    
    <div class="row">
        <div class="col-md-4">
            <h2>{{ product.name }}</h2>
            <h5>{{ product.review_set.count }} reviews ({{ product.average_rating | floatformat }} average rating)</h5> {% if product.image %}
            <a href="#" class="thumbnail">
                <img src='{{ product.image.url }}' class='img-responsive' alt="...">
            </a>
            {% endif %}
        </div>
    </div>
    
    <div class="product-wrap">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-6">
                <h3>About</h3>
                {% if product.description %}
                <em><h4>{{ product.description }}</h4></em>
                {% endif %}
                <h3>Helpful Links</h3> {% if product.link1_title %} {% if product.link1_link %}
                <h4><a href="{{product.link1_link}}" target="_top">{{product.link1_title}}</a></h4> {% endif %} {% endif %}
                <br> {% if product.link2_title %} {% if product.link2_link %}
                <h4><a href="{{product.link2_link}}" target="_top">{{product.link2_title}}</a></h4> {% endif %} {% endif %}
            </div>
            <div class="col-md-3 col-sm-4 col-xs-6">
                <h3>Recent reviews</h3> {% if product.review_set.all %} {% for review in product.review_set.all %}
                <div>
                    <em>{{ review.comment }}</em>
                    <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
                    <h5><a href="{% url 'web:review_detail' review.id %}">
                                        Read more
                                        </a></h5>
                </div>
                {% endfor %} {% else %}
                <p>No reviews for this product yet</p>
                {% endif %}


                <h3>Add your review</h3> {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>{% endif %}

                <form action="{% url 'web:add_review' product.id %}" method="post" class="form">
                    {% csrf_token %} {% for field in form %} {% bootstrap_field field %} {% endfor %} {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Add
                    </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

web/templates/web/product_list.html
{% extends 'web/base.html' %}

{% block title %}

{% endblock %}

{% block content %}
<div class="page-header">
      <h3>Our Products</h3><h4>(Click product for reviews and details)</h4>
    </div>

<div class="container-fluid">

{% if product_list %}
<div class="row">
    {% for product in product_list %}
    <div class="col-md-3 col-sm-4 col-xs-6">
        <div class="product-list-image">
        {% if product.image %}
        <a href="{% url 'web:product_detail' product.id %}" class="thumbnail">
      <img src='{{ product.image.url }}' class='img-responsive'  alt="...">
    </a>
        {% endif %}
        </div>
        <h4><a href="{% url 'web:product_detail' product.id %}">
        {{ product.name }}
        </a></h4>
        <h5>{{ product.review_set.count }} reviews</h5>
        <h5>{{ product.average_rating | floatformat}} average rating</h5>
    </div>
    {% endfor %}
    
</div>
{% else %}
    <p>No products are available.</p>
{% endif %}
</div>
{% endblock %}

web/templates/web/review_detail.html
{% extends 'web/base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="review-detail">
<h2><a href="{% url 'web:product_detail' review.product.id %}">{{ review.product.name }}</a></h2>
<h4>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
</div>
</div>
{% endblock %}

web/templates/web/review_list.html
{% extends 'web/base.html' %}

{% block title %}
{% endblock %}

<div class="page-header">
      <h3>Home</h3>
    </div>

{% block content %}
    <div class="container-fluid">
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-md-3">
        <h4><a href="{% url 'web:review_detail' review.id %}">
        {{ review.product.name }}
        </a></h4>
        <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
        </div>
{% endblock %}

web/templates/web/why_detail.html
{% extends 'web/base.html' %}
{% load staticfiles %}

{% block title %}
<!--<h2>Why Organic??</h2>-->
{% endblock %}

{% block content %}
<body>
    <div class="page-header">

        <h3>Safe & Healthy Food</h3>

    </div>

    <div class="post">

        <div class="row">
            <div class="col-md-4">
                <blockquote class="blockquote">
                    <p class="m-b-0">"We make our decisions, and then our decisions turn around and make us."</p>
                    <footer class="blockquote-footer">F.W. Boreham <cite title="Source Title"></cite></footer>
                </blockquote>
            </div>
            <div class="col-md-4">
                <blockquote class="blockquote">
                    <p class="m-b-0">"Every time you buy local you're persuading more farmers to grow locally."</p>
                    <footer class="blockquote-footer">Mother Earth News</footer>
                </blockquote>
            </div>
            <div class="col-md-4">
                <blockquote class="blockquote">
                    <p class="m-b-0">"Take care of your body. It's the only place you have to live in."</p>
                    <footer class="blockquote-footer">humanresourcesblog</footer>
                </blockquote>
            </div>
        </div>
        <div class="row">
            <h1>You are what you eat. Healthy food choices will be made only after you learn the truth.</h1>
            <br>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="video-attributes">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/5444xRrdITw" frameborder="0" allowfullscreen></iframe>
                    <h3>Video 1: Chronic Dietary Exposure to Pesticide Residules in the United States</h3> Dr. Carl Winter, Department of Food Science and Technology International Journal of Food Consumption
                </div>
            </div>
            <div class="col-md-6">
                <div class="video-attributes">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/QqQVll-MP3I" frameborder="0" allowfullscreen></iframe>

                    <h3>Video 2: The Truth About Your Food with FOOD, INC. </h3> Made by Filmmaker Robert Kenner
                </div>
            </div>
        </div>
    </div>

    <div class="post">



        <h2>Checkout:</h2>

        <h4><a href="http://www.webmd.com/diet/features/safer-food-healthier-you#1" target="_blank">Safer Food for a Healthier You</a></h4>


    </div>
    <div class="plantbg">

        <h1>Love the stuff that you eat!</h1>

    </div>

</body>
{% endblock %}